version: "3.9"
services:
    laravel_db:
        image: mysql:5.7.33
        volumes:
            - ./infra/docker/mysql/volume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
            TZ: 'Asia/Tokyo'
        ports:
            - "3306:3306"

    laravel_adminer:
        image: adminer:4.8.0
        ports:
            - "8081:8080"
        depends_on:
            - laravel_db

    laravel_mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"

    laravel_php:
        image: laravel-php:7.3.28-apache-composer-2.0.13
        build:
            context: .
            dockerfile: ./infra/docker/Dockerfile
        volumes:
            - ./backend:/home/laravel/project
        environment:
            - SESSION_DRIVER=${SESSION_DRIVER:-redis}
            - SESSION_LIFETIME=${SESSION_LIFETIME:-120}
        XDEBUG_CONFIG: client_host=host.docker.internal
        ports:
            - "8080:80"
        depends_on:
            - laravel_db
            - laravel_mailhog

    laravel_cache:
        image: redis:6.2.4-alpine