version: "3.9"

volumes:
  cache_volume:

services:
    laravel_db:
        platform: linux/x86_64
        image: mysql:5.7.33
        volumes:
            - ./infra/docker/mysql/volume:/var/lib/mysql
            - ./infra/docker/mysql/my.cnf:/etc/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
            TZ: 'Asia/Tokyo'
        ports:
            - "3306:3306"
        restart: always

    laravel_adminer:
        image: adminer:4.8.0
        ports:
            - "8081:8080"
        depends_on:
            - laravel_db
        restart: always

    laravel_mailhog:
        platform: linux/x86_64
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        restart: always

    laravel_php:
        image: laravel-php:7.3.28-apache-composer-2.0.13
        build:
            context: .
            dockerfile: ./infra/docker/Dockerfile
        volumes:
            - ./backend:/home/laravel/project
        environment:
            XDEBUG_CONFIG: client_host=host.docker.internal
            SESSION_DRIVER: ${SESSION_DRIVER:-redis}
            SESSION_LIFETIME: ${SESSION_LIFETIME:-120}
        ports:
            - "8080:80"
        depends_on:
            - laravel_db
            - laravel_mailhog
        restart: always

    laravel_cache:
        image: redis:latest
        volumes:
            - cache_volume:/data
        restart: always
