volumes:
  php-fpm-socket:
  postgres-store:
  postgres-test-store:
  cache_volume:
  public-storage:

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - public-storage:/work/backend/storage/app/public
    #volumes:
      #- ./backend:/work/backend
    environment:
      - APP_ENV=${APP_ENV:-local}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-laravel_local}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - MAIL_MAILER=${MAIL_MAILER:-smtp}
      - REDIS_HOST=cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

  scheduler:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    env_file:
      - ./backend/.env
    command: php artisan schedule:work
    working_dir: /work/backend
    restart: unless-stopped
    depends_on:
      - app
      - db
      - cache
    environment:
      - APP_ENV=${APP_ENV:-local}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-laravel_local}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - MAIL_MAILER=${MAIL_MAILER:-smtp}
      - REDIS_HOST=cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

  queue:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    env_file:
      - ./backend/.env
    command: php artisan queue:work database --tries=6 --delay=60
    working_dir: /work/backend
    restart: unless-stopped
    depends_on:
      - app
      - db
      - cache
    environment:
      - APP_ENV=${APP_ENV:-local}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-5432}
      - DB_DATABASE=${DB_DATABASE:-laravel_local}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - MAIL_MAILER=${MAIL_MAILER:-smtp}
      - REDIS_HOST=cache
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - public-storage:/var/www/project/storage/app/public
    #volumes:
      #- ./backend:/work/backend
    ports:
      - target: 80
        published: ${WEB_PORT:-8080}
        protocol: tcp
        mode: host

  db:
    image: postgres:16
    ports:
      - target: 5432
        published: ${DB_PUBLISHED_PORT:-5433}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: postgres-store
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    environment:
      - POSTGRES_DB=${DB_DATABASE:-laravel_local}
      - POSTGRES_USER=${DB_USERNAME:-phper}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  db.test:
    image: postgres:16
    environment:
      POSTGRES_DB: '${DB_DATABASE_TEST:-laravel_test}'
      POSTGRES_USER: '${DB_USERNAME:-phper}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - type: volume
        source: postgres-test-store
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  selenium:
    image: seleniarm/standalone-chromium
    #image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: '2gb'

  cache:
    image: redis:latest
    volumes:
      - type: volume
        source: cache_volume
        target: /data
        volume:
          nocopy: true

  laravel_adminer:
    image: adminer:4.8.0
    ports:
        - "8081:8080"
    depends_on:
        - db
        - db.test
    restart: always

  laravel_mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    ports:
        - "1025:1025"
        - "8025:8025"
    restart: always

networks:
  default:
    ipam:
      config:
        - subnet: ${VPC_CIDR:-171.32.0.0/16}
