volumes:
  php-fpm-socket:
  db-store:
  db-test-store:
  cache_volume:
  public-storage:

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    restart: unless-stopped
    command: >
      sh -lc "mkdir -p /work/backend/storage/app/public/images
      && chown -R www-data:www-data /work/backend/storage/app/public
      && chmod -R u=rwX,g=rX,o=rX /work/backend/storage/app/public
      && php-fpm"
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - public-storage:/work/backend/storage/app/public

  scheduler:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    command: php artisan schedule:work
    working_dir: /work/backend
    restart: unless-stopped
    depends_on:
      - app
      - db
      - cache

  queue:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    command: php artisan queue:work redis --tries=6 --delay=60
    working_dir: /work/backend
    restart: unless-stopped
    depends_on:
      - app
      - db
      - cache

  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - public-storage:/work/backend/storage/app/public
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - target: 3306
        published: 3307
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=laravel_local
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      retries: 3
      start_period: 5s

  db.test:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    restart: unless-stopped
    volumes:
      - type: volume
        source: db-test-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: laravel_test
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-psecret"]
      retries: 3
      start_period: 5s

  selenium:
    image: seleniarm/standalone-chromium
    restart: unless-stopped
    ports:
      - "4444:4444"
    shm_size: '2gb'

  cache:
    image: redis:6.2.4-alpine
    restart: unless-stopped
    volumes:
      - type: volume
        source: cache_volume
        target: /data
        volume:
          nocopy: true

  laravel_adminer:
    image: adminer:4.8.0
    ports:
        - "8081:8080"
    depends_on:
        - db
        - db.test
    restart: unless-stopped

  laravel_mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog
    ports:
        - "1025:1025"
        - "8025:8025"
    restart: unless-stopped
